//! Integration tests for `signex_library::ai_stub`.
//!
//! Uses synthetic PDF fixtures generated by `pdf-writer` (a workspace
//! dev-dep). The fixtures are written into
//! `tests/fixtures/datasheets/` on first run, so the repository can be
//! checked out without binary blobs and the tests will hydrate them.
//!
//! Run with: `cargo test -p signex-library --features ai-stub`.

#![cfg(feature = "ai-stub")]

use signex_library::{PinoutGuess, extract_pinout};
use std::path::{Path, PathBuf};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("datasheets")
}

fn ensure_fixtures() {
    let dir = fixtures_dir();
    std::fs::create_dir_all(&dir).expect("create fixtures dir");

    let lm317 = dir.join("lm317.pdf");
    if !lm317.exists() {
        let bytes = generate_lm317_pdf();
        std::fs::write(&lm317, &bytes).expect("write lm317.pdf");
    }

    let garbage = dir.join("garbage.pdf");
    if !garbage.exists() {
        let bytes = generate_garbage_pdf();
        std::fs::write(&garbage, &bytes).expect("write garbage.pdf");
    }
}

/// Build a small synthetic LM317-style datasheet PDF.
///
/// The PDF embeds a textual pin table in a content stream so
/// `pdf_extract::extract_text_from_mem` will recover line-by-line text.
fn generate_lm317_pdf() -> Vec<u8> {
    // Lines the heuristic should latch onto. Order doesn't matter — the
    // extractor dedupes by pin number.
    let pin_lines = [
        "LM317 Pin Configuration",
        "Pin  Name  Function",
        "1 ADJ Adjustment terminal sets output voltage",
        "2 OUT Regulated output voltage of the device",
        "3 IN  Unregulated input voltage to the regulator",
    ];
    build_text_only_pdf(&pin_lines)
}

/// Build a minimal "garbage" PDF — text content with no pin-table rows.
fn generate_garbage_pdf() -> Vec<u8> {
    let lines = [
        "Lorem ipsum dolor sit amet",
        "consectetur adipiscing elit",
        "Order today for special pricing",
    ];
    build_text_only_pdf(&lines)
}

/// Emit a single-page PDF whose content stream draws each `line` on a
/// successive baseline using the standard-14 Helvetica font.
fn build_text_only_pdf(lines: &[&str]) -> Vec<u8> {
    use pdf_writer::{Content, Finish, Name, Pdf, Rect, Ref, Str};

    let mut pdf = Pdf::new();

    let catalog_id = Ref::new(1);
    let page_tree_id = Ref::new(2);
    let page_id = Ref::new(3);
    let content_id = Ref::new(4);
    let font_id = Ref::new(5);

    pdf.catalog(catalog_id).pages(page_tree_id);
    pdf.pages(page_tree_id).kids([page_id]).count(1);

    let mut page = pdf.page(page_id);
    page.parent(page_tree_id)
        .media_box(Rect::new(0.0, 0.0, 612.0, 792.0))
        .contents(content_id);
    let mut resources = page.resources();
    resources.fonts().pair(Name(b"F1"), font_id).finish();
    resources.finish();
    page.finish();

    pdf.type1_font(font_id).base_font(Name(b"Helvetica"));

    // Content stream: BT / Tf / Td / Tj / ET, one line per row.
    let mut content = Content::new();
    content.begin_text();
    content.set_font(Name(b"F1"), 12.0);
    // Start near the top of the page in PDF user units (points).
    content.next_line(72.0, 720.0);
    for (i, line) in lines.iter().enumerate() {
        if i == 0 {
            // First line — already at start position.
            content.show(Str(line.as_bytes()));
        } else {
            // Drop one line (~14 pt) and emit.
            content.next_line(0.0, -14.0);
            content.show(Str(line.as_bytes()));
        }
    }
    content.end_text();
    pdf.stream(content_id, &content.finish());

    pdf.finish()
}

#[test]
fn lm317_fixture_returns_three_pins_with_high_confidence() {
    ensure_fixtures();
    let path = fixtures_dir().join("lm317.pdf");
    let bytes = std::fs::read(&path).expect("read lm317.pdf");

    // Acceptance: pin-count = 3 with confidence ≥ 0.7.
    assert!(
        bytes.len() < 50 * 1024,
        "fixture must stay below 50 KB (got {} B)",
        bytes.len()
    );

    let guess: PinoutGuess = extract_pinout(&bytes);
    assert!(
        guess.confidence >= 0.7,
        "LM317 confidence {} should be ≥ 0.7 (pins={:?})",
        guess.confidence,
        guess.pins
    );
    assert_eq!(
        guess.pins.len(),
        3,
        "expected 3 pins, got {} ({:?})",
        guess.pins.len(),
        guess.pins
    );
    let names: Vec<&str> = guess.pins.iter().map(|p| p.name.as_str()).collect();
    for expected in ["ADJ", "OUT", "IN"] {
        assert!(
            names.contains(&expected),
            "expected pin name {expected} in {names:?}"
        );
    }
}

#[test]
fn garbage_fixture_returns_no_pins_with_low_confidence() {
    ensure_fixtures();
    let path: PathBuf = fixtures_dir().join("garbage.pdf");
    let bytes = std::fs::read(&path).expect("read garbage.pdf");

    assert!(
        bytes.len() < 50 * 1024,
        "fixture must stay below 50 KB (got {} B)",
        bytes.len()
    );

    let guess = extract_pinout(&bytes);
    assert!(
        guess.pins.is_empty(),
        "garbage PDF should yield no pins, got {:?}",
        guess.pins
    );
    assert!(
        guess.confidence < 0.3,
        "garbage confidence {} should be < 0.3",
        guess.confidence
    );
}

#[test]
fn extract_pinout_handles_corrupt_bytes_gracefully() {
    // Bare bytes that are *not* a PDF — must not panic, must report
    // a low-confidence empty result.
    let bytes = b"this is not a pdf at all";
    let guess = extract_pinout(bytes);
    assert!(guess.pins.is_empty());
    assert!(guess.confidence < 0.3);
}

#[test]
fn extract_pinout_is_pure_no_panic_on_empty_input() {
    let guess = extract_pinout(&[]);
    assert!(guess.pins.is_empty());
    assert!(guess.confidence < 0.3);
}

#[allow(dead_code)]
fn _exhaustive_path_check(_p: &Path) {
    // Compile-only: ensure the `Path` import stays referenced when
    // `ensure_fixtures` body changes.
}
