//! Footprint v1 → v2 schema migration tests.
//!
//! Tasks 5.1 + 5.2 of `SKETCH_MODE_v0.13_PLAN.md`: the `Footprint`
//! struct gained `schema_version: u32` and `sketch:
//! Option<SketchData>` in v0.13. Legacy v1 footprints written
//! before those fields existed must still deserialise cleanly,
//! defaulting to `schema_version = 2` and `sketch = None`. This
//! file exercises three real-world v1 fixtures (SOIC-8, QFP-32,
//! mounting hole + fiducials) and a v2 round-trip with a non-empty
//! sketch.
//!
//! The fixtures live under `tests/fixtures/` and were authored by
//! hand — *not* generated by serialising a live `Footprint` —
//! precisely so the test proves a TOML written before
//! `schema_version` and `sketch` existed still loads.

use signex_library::primitive::footprint::Footprint;
use signex_sketch::SketchData;

#[test]
fn v1_soic8_loads_with_no_sketch_and_schema_2() {
    let toml_src = include_str!("fixtures/v1_soic8.toml");
    let fp: Footprint = toml::from_str(toml_src).expect("v1 SOIC-8 must deserialise into v2");
    assert_eq!(
        fp.schema_version, 2,
        "default schema_version applies to legacy fixtures"
    );
    assert!(fp.sketch.is_none(), "v1 footprints have no sketch");
    assert_eq!(fp.pads.len(), 8, "SOIC-8 has 8 pads");
    assert_eq!(fp.name, "SOIC-8");
}

#[test]
fn v1_qfp32_loads_clean() {
    let toml_src = include_str!("fixtures/v1_qfp32.toml");
    let fp: Footprint = toml::from_str(toml_src).expect("v1 QFP-32 must deserialise into v2");
    assert_eq!(fp.schema_version, 2);
    assert!(fp.sketch.is_none());
    assert_eq!(fp.pads.len(), 32, "QFP-32 has 4×8 = 32 pads");
    assert_eq!(fp.name, "QFP-32");
}

#[test]
fn v1_mounting_hole_loads_clean() {
    let toml_src = include_str!("fixtures/v1_mounting_hole.toml");
    let fp: Footprint =
        toml::from_str(toml_src).expect("v1 mounting hole must deserialise into v2");
    assert_eq!(fp.schema_version, 2);
    assert!(fp.sketch.is_none());
    assert_eq!(fp.pads.len(), 5, "1 NPT hole + 4 fiducials");
    // First pad is the NPT hole; verify the drill survived deserialisation.
    let mh = &fp.pads[0];
    assert_eq!(mh.number, "MH1");
    let drill = mh.drill.as_ref().expect("NPT pad must carry a drill spec");
    assert!((drill.diameter - 3.2).abs() < f64::EPSILON);
}

#[test]
fn v2_round_trip_with_sketch() {
    let toml_src = include_str!("fixtures/v1_soic8.toml");
    let mut fp: Footprint = toml::from_str(toml_src).unwrap();
    fp.sketch = Some(SketchData::default());

    let serialised = toml::to_string(&fp).expect("v2 footprint with sketch must serialise");
    let back: Footprint =
        toml::from_str(&serialised).expect("serialised v2 footprint must round-trip");

    assert!(
        back.sketch.is_some(),
        "sketch field must survive round-trip"
    );
    assert_eq!(back.schema_version, 2);
    assert_eq!(back, fp, "round-trip must preserve every field");
}

#[test]
fn v2_serialises_skips_none_sketch() {
    let toml_src = include_str!("fixtures/v1_soic8.toml");
    let fp: Footprint = toml::from_str(toml_src).unwrap();
    let out = toml::to_string(&fp).unwrap();
    assert!(
        !out.contains("sketch"),
        "sketch=None must skip serialisation entirely; got:\n{}",
        out
    );
}
