//! Build script for signex-app.
//!
//! - Declares the custom cfg `has_bundled_icon`, set when a pre-rendered 256px
//!   PNG exists at `assets/brand/generated/signex-256.png`. The runtime window
//!   icon in `bootstrap.rs` is gated on this cfg, so the app compiles and runs
//!   both before and after the icon bitmaps are generated by
//!   `installer/build-icons.sh`.
//! - On Windows, embeds `installer/windows/signex.ico` into `signex.exe` via
//!   `winres`, if the .ico file is present. The installer falls back gracefully
//!   when it isn't.

use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rustc-check-cfg=cfg(has_bundled_icon)");

    let png = Path::new("assets/brand/generated/signex-256.png");
    if png.exists() {
        println!("cargo:rustc-cfg=has_bundled_icon");
    }
    println!("cargo:rerun-if-changed=assets/brand/generated/signex-256.png");

    embed_windows_exe_icon();
}

#[cfg(windows)]
fn embed_windows_exe_icon() {
    let ico = Path::new("../../installer/windows/signex.ico");
    println!("cargo:rerun-if-changed=../../installer/windows/signex.ico");
    if !ico.exists() {
        return;
    }
    let mut res = winres::WindowsResource::new();
    res.set_icon(ico.to_str().expect("ico path is valid UTF-8"));
    if let Err(e) = res.compile() {
        // Don't fail the build over this — the app still runs, just without
        // an embedded Explorer/taskbar icon.
        eprintln!("cargo:warning=winres failed to embed icon: {e}");
    }
}

#[cfg(not(windows))]
fn embed_windows_exe_icon() {}
