use crate::transmission_line_calculator::{
    CustomInterpolation, FrequencyScale, ScalarUnit, SmithViewTransform, TransformerModel,
};
use iced::widget::text_editor;

use crate::transmission_line_calculator::tool::component_editor::{
    CircuitComponentField, CircuitComponentKind,
};
use crate::transmission_line_calculator::tool::results::ResultDiagramKind;

use super::SmithChartDiagramMode;

/// Describes every user-interface action that can update the calculator state.
#[derive(Debug, Clone)]
pub enum SmithChartMessage {
    AddCircuitComponent(CircuitComponentKind),
    CircuitComponentFieldChanged {
        index: usize,
        field: CircuitComponentField,
        value: String,
    },
    CircuitInterpolationChanged(usize, CustomInterpolation),
    CircuitTransformerModelChanged(usize, TransformerModel),
    MoveCircuitComponentLeft(usize),
    MoveCircuitComponentRight(usize),
    RemoveCircuitComponent(usize),
    LoadReChanged(String),
    LoadImChanged(String),
    LoadToleranceChanged(String),
    LoadReSliderChanged(String),
    LoadImSliderChanged(String),
    FrequencyMhzChanged(String),
    FrequencyUnitChanged(ScalarUnit),
    ReferenceOhmChanged(String),
    SpanMhzChanged(String),
    SpanUnitChanged(ScalarUnit),
    ResolutionChanged(String),
    ShowIdealChanged(bool),
    DiagramModeChanged(SmithChartDiagramMode),
    SmithSphereRotationChanged {
        yaw: f32,
        pitch: f32,
    },
    ResetSmithSphereRotation,
    SmithViewTransformChanged(SmithViewTransform),
    ResetSmithViewTransform,
    ShowGridChanged(bool),
    ShowAdmittanceChanged(bool),
    ShowVswrChanged(bool),
    ShowQChanged(bool),
    ShowStabilityCirclesChanged(bool),
    ShowS11TraceChanged(bool),
    ShowS21TraceChanged(bool),
    ShowS12TraceChanged(bool),
    ShowS22TraceChanged(bool),
    ConjugateSParameterTracesChanged(bool),
    VswrCircleInputDbChanged(bool),
    ResistanceLabelListChanged(String),
    ReactanceLabelListChanged(String),
    MarkerListChanged(String),
    QCircleListChanged(String),
    VswrCircleListChanged(String),
    NoiseFigureCircleListChanged(String),
    GainInputCircleListChanged(String),
    GainOutputCircleListChanged(String),
    SeriesResistanceEnabled(bool),
    SeriesResistanceChanged(String),
    SeriesResistanceEslNhChanged(String),
    SeriesResistanceToleranceChanged(String),
    SeriesResistanceSliderChanged(String),
    ShuntResistanceEnabled(bool),
    ShuntResistanceChanged(String),
    ShuntResistanceEslNhChanged(String),
    ShuntResistanceToleranceChanged(String),
    ShuntResistanceSliderChanged(String),
    SeriesInductanceEnabled(bool),
    SeriesInductanceNhChanged(String),
    SeriesInductanceEsrChanged(String),
    SeriesInductanceToleranceChanged(String),
    SeriesInductanceSliderChanged(String),
    ShuntInductanceEnabled(bool),
    ShuntInductanceNhChanged(String),
    ShuntInductanceEsrChanged(String),
    ShuntInductanceToleranceChanged(String),
    ShuntInductanceSliderChanged(String),
    SeriesCapacitanceEnabled(bool),
    SeriesCapacitancePfChanged(String),
    SeriesCapacitanceEsrChanged(String),
    SeriesCapacitanceEslNhChanged(String),
    SeriesCapacitanceToleranceChanged(String),
    SeriesCapacitanceSliderChanged(String),
    ShuntCapacitanceEnabled(bool),
    ShuntCapacitancePfChanged(String),
    ShuntCapacitanceEsrChanged(String),
    ShuntCapacitanceEslNhChanged(String),
    ShuntCapacitanceToleranceChanged(String),
    ShuntCapacitanceSliderChanged(String),
    RlcEnabled(bool),
    RlcResistanceChanged(String),
    RlcInductanceNhChanged(String),
    RlcCapacitancePfChanged(String),
    RlcResistanceSliderChanged(String),
    LineEnabled(bool),
    LineLengthMmChanged(String),
    LineImpedanceChanged(String),
    LineEeffChanged(String),
    LineToleranceChanged(String),
    LineLengthSliderChanged(String),
    OpenStubEnabled(bool),
    OpenStubLengthMmChanged(String),
    OpenStubImpedanceChanged(String),
    OpenStubEeffChanged(String),
    OpenStubToleranceChanged(String),
    OpenStubLengthSliderChanged(String),
    ShortStubEnabled(bool),
    ShortStubLengthMmChanged(String),
    ShortStubImpedanceChanged(String),
    ShortStubEeffChanged(String),
    ShortStubToleranceChanged(String),
    ShortStubLengthSliderChanged(String),
    TransformerEnabled(bool),
    TransformerModelChanged(TransformerModel),
    TransformerRatioChanged(String),
    TransformerL1NhChanged(String),
    TransformerL2NhChanged(String),
    TransformerCouplingChanged(String),
    CustomEnabled(bool),
    CustomInterpolationChanged(CustomInterpolation),
    CustomPointsChanged(String),
    SParameterEnabled(bool),
    SParameterTextChanged(String),
    SParameterTextAction(text_editor::Action),
    ImportSParameterFile,
    SParameterFileLoaded(Result<Option<String>, String>),
    OrderedCircuitEnabled(bool),
    OrderedCircuitTokensChanged(String),
    OrderedCircuitRowChanged(usize, String),
    AddOrderedCircuitRow(&'static str),
    MoveOrderedCircuitRowUp(usize),
    MoveOrderedCircuitRowDown(usize),
    RemoveOrderedCircuitRow(usize),
    LoadCompactCircuitIntoOrderedRows,
    OpenCsvExport(ResultDiagramKind),
    CsvExportStartFrequencyChanged(String),
    CsvExportStopFrequencyChanged(String),
    CsvExportStartFrequencyUnitChanged(ScalarUnit),
    CsvExportStopFrequencyUnitChanged(ScalarUnit),
    CsvExportOutputFrequencyUnitChanged(ScalarUnit),
    CsvExportSamplesChanged(String),
    ResultFrequencyScaleChanged(FrequencyScale),
    CancelCsvExport,
    SaveCsvFile,
    CsvFileSaved(Result<Option<String>, String>),
    SaveSvgFile,
    SvgFileSaved(Result<Option<String>, String>),
    Reset,
}
