//! General-surface command metadata — shared editing / file / view /
//! transform commands, plus anything without an obvious home. Split
//! from `keymap/catalog.rs`; entries verbatim.

use super::{CommandGroup, CommandMetadata};

pub(super) const GENERAL: &[CommandMetadata] = &[
    CommandMetadata {
        id: "autoplace_fields",
        category: "edit",
        label: "Autoplace fields",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "break_wire",
        category: "modify",
        label: "Break wire",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "cancel_current_tool",
        category: "interactive",
        label: "Cancel current stage / exit placement mode",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "center_on_cursor",
        category: "view",
        label: "Center on cursor",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "center_view_at_cursor",
        category: "view",
        label: "Center/redraw view around cursor",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "close_active_document",
        category: "file",
        label: "Close active document",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "copy",
        category: "edit",
        label: "Copy",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "copy_attributes_or_add_vertex",
        category: "interactive",
        label: "Copy attributes from object under cursor or add vertex while drawing",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "cut",
        category: "edit",
        label: "Cut",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "cycle_fast_grid",
        category: "view",
        label: "Cycle fast grid",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "cycle_unit",
        category: "view",
        label: "Cycle display unit",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "cycle_snap_grid_backward",
        category: "view",
        label: "Cycle backward through snap grids",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "cycle_selection_mode",
        category: "select",
        label: "Cycle selection mode",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "cycle_snap_grid_forward",
        category: "view",
        label: "Cycle forward through snap grids",
        menu_label: Some("Cycle Grid Size"),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "cycle_wire_bus_graphic_mode",
        category: "interactive",
        label: "Cycle wire/bus/graphic-line mode: free, 90 degrees, 45 degrees",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "cycle_wiring_mode",
        category: "interactive",
        label: "Change wiring mode while dragging connected electrical objects",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "delete_selection",
        category: "edit",
        label: "Delete selection",
        menu_label: Some("Delete"),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "drag_keep_connections",
        category: "modify",
        label: "Drag while keeping connections",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "duplicate",
        category: "edit",
        label: "Duplicate",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "edit_footprint_field",
        category: "edit",
        label: "Edit footprint field",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "edit_library_symbol",
        category: "library",
        label: "Edit library symbol",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "edit_object_properties",
        category: "edit",
        label: "Edit properties of object under cursor",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "edit_reference_designator",
        category: "edit",
        label: "Edit reference designator",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "edit_selected_object_properties",
        category: "edit",
        label: "Properties / edit selected object",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "edit_selected_symbol_in_symbol_editor",
        category: "library",
        label: "Edit selected symbol in Symbol Editor",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "edit_text_in_place",
        category: "edit",
        label: "In-place edit selected text",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "edit_value",
        category: "edit",
        label: "Edit value",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "fast_grid_1",
        category: "view",
        label: "Fast grid 1",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "fast_grid_2",
        category: "view",
        label: "Fast grid 2",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "find",
        category: "search",
        label: "Find",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "find_and_replace",
        category: "search",
        label: "Find and replace",
        menu_label: Some("Find and Replace"),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "find_next",
        category: "search",
        label: "Find next",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "find_previous",
        category: "search",
        label: "Find previous",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "find_similar_objects",
        category: "select",
        label: "Find Similar Objects",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "find_text",
        category: "search",
        label: "Find text",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "import_graphics",
        category: "library",
        label: "Import graphics",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "measure_distance",
        category: "view",
        label: "Measure distance",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "mirror_x",
        category: "modify",
        label: "Mirror along X-axis",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "mirror_y",
        category: "modify",
        label: "Mirror along Y-axis",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "move_object",
        category: "modify",
        label: "Move object",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "move_selection",
        category: "modify",
        label: "Move",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "new_document",
        category: "file",
        label: "New",
        menu_label: Some("New Project"),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "next_document_tab",
        category: "window",
        label: "Next open document tab",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "next_grid",
        category: "view",
        label: "Next grid",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "open_command_palette",
        category: "commands",
        label: "Open command palette",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "open_datasheet",
        category: "edit",
        label: "Open datasheet",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "open_document",
        category: "file",
        label: "Open document",
        menu_label: Some("Open..."),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "open_grid_picker",
        category: "view",
        label: "Open grid picker",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "open_grid_properties",
        category: "view",
        label: "Open grid properties",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "open_preferences",
        category: "preferences",
        label: "Open preferences",
        menu_label: Some("Preferences..."),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "open_schematic_preferences",
        category: "preferences",
        label: "Open schematic preferences",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "paste",
        category: "edit",
        label: "Paste",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "paste_special",
        category: "edit",
        label: "Paste special",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "placement_accept",
        category: "interactive",
        label: "Accept current placement or move stage",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "placement_properties",
        category: "interactive",
        label: "Edit properties of the object being placed or moved",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "previous_document_tab",
        category: "window",
        label: "Previous open document tab",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "previous_grid",
        category: "view",
        label: "Previous grid",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "print",
        category: "file",
        label: "Print",
        menu_label: Some("PDF…"),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "redo",
        category: "edit",
        label: "Redo",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "refresh_view",
        category: "view",
        label: "Refresh/redraw",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "remove_last_vertex",
        category: "interactive",
        label: "Remove last placed vertex while drawing",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "repeat_last_item",
        category: "edit",
        label: "Repeat last item",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "report_manager_bom",
        category: "reports",
        label: "Report Manager / BOM",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "reset_local_coordinates",
        category: "view",
        label: "Reset local coordinates",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "rotate_clockwise",
        category: "modify",
        label: "Rotate clockwise by 90 degrees",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "rotate_counterclockwise",
        category: "modify",
        label: "Rotate counterclockwise by 90 degrees",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "rubber_stamp_copy",
        category: "edit",
        label: "Rubber-stamp copy / repeated paste",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "save_document",
        category: "file",
        label: "Save document",
        menu_label: Some("Save"),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "save_document_as",
        category: "file",
        label: "Save as",
        menu_label: Some("Save As..."),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "select_all",
        category: "select",
        label: "Select all",
        menu_label: Some("Select All"),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "select_expand_connection",
        category: "select",
        label: "Select / expand connection",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "select_node_or_connection_item",
        category: "select",
        label: "Select node / connection item under cursor",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "show_all_design_objects",
        category: "view",
        label: "Show all design objects",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "show_current_command_hotkeys",
        category: "help",
        label: "Show graphical editing hotkey list for current command",
        menu_label: Some("Keyboard Shortcuts"),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "show_current_command_shortcuts",
        category: "help",
        label: "Show valid shortcuts for the current interactive command",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "smart_paste",
        category: "edit",
        label: "Smart Paste",
        menu_label: Some("Paste Special"),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "switch_segment_posture",
        category: "interactive",
        label: "Switch current segment posture",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "toggle_cross_select_mode",
        category: "select",
        label: "Toggle Cross Select Mode",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "toggle_electrical_grid",
        category: "view",
        label: "Toggle electrical grid",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "toggle_floating_panels",
        category: "window",
        label: "Toggle floating panels",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "toggle_properties_panel",
        category: "panels",
        label: "Toggle Properties panel",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "toggle_schematic_filter_panel",
        category: "panels",
        label: "Toggle schematic filter panel",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "toggle_schematic_list_panel",
        category: "panels",
        label: "Toggle schematic list panel",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "toggle_search_panel",
        category: "search",
        label: "Show/hide search panel",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "toggle_selection",
        category: "select",
        label: "Add/remove object from selection",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "toggle_auto_focus",
        category: "view",
        label: "Toggle AutoFocus",
        menu_label: Some("AutoFocus (dim unselected)"),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "toggle_visible_grid",
        category: "view",
        label: "Toggle visible grid",
        menu_label: Some("Toggle Grid"),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "undo",
        category: "edit",
        label: "Undo",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "undo_last_segment",
        category: "interactive",
        label: "Undo last segment while drawing",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "unselect_all",
        category: "select",
        label: "Unselect all",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "zoom_in_at_cursor",
        category: "view",
        label: "Zoom in at cursor",
        menu_label: Some("Zoom In"),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "zoom_out_at_cursor",
        category: "view",
        label: "Zoom out at cursor",
        menu_label: Some("Zoom Out"),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "zoom_to_all_objects",
        category: "view",
        label: "Zoom to all objects",
        menu_label: None,
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "zoom_to_fit",
        category: "view",
        label: "Zoom to fit",
        menu_label: Some("Fit All"),
        group: CommandGroup::General,
    },
    CommandMetadata {
        id: "zoom_to_selection_area",
        category: "view",
        label: "Zoom to selection area",
        menu_label: None,
        group: CommandGroup::General,
    },
];
