//! Schematic-surface command metadata — placement, net, annotation,
//! sheet-navigation. Split from `keymap/catalog.rs`; entries verbatim.

use super::{CommandGroup, CommandMetadata};

pub(super) const SCHEMATIC: &[CommandMetadata] = &[
    CommandMetadata {
        id: "annotate_schematic",
        category: "design",
        label: "Annotate schematic",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "annotate_schematic_quietly",
        category: "design",
        label: "Annotate schematic quietly",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "clear_net_highlighting",
        category: "select",
        label: "Clear net highlighting",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "draw_graphic_line",
        category: "place",
        label: "Draw graphic line",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "draw_hierarchical_sheet",
        category: "place",
        label: "Draw hierarchical sheet",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "force_annotate_all_schematics",
        category: "design",
        label: "Force annotate all schematics",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "highlight_net_under_cursor",
        category: "select",
        label: "Highlight net under cursor",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "highlight_related_net_objects",
        category: "select",
        label: "Highlight/select related net objects across sheets",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "leave_sheet",
        category: "navigation",
        label: "Leave sheet / go to parent sheet",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "navigate_up_hierarchy",
        category: "navigation",
        label: "Navigate up hierarchy",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "next_highlighted_net_item",
        category: "select",
        label: "Next item on highlighted net",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "next_sheet",
        category: "navigation",
        label: "Next sheet",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "open_components_panel",
        category: "panels",
        label: "Open Components panel / place components",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "open_net_color_palette",
        category: "view",
        label: "Open net color palette",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "place_bus",
        category: "place",
        label: "Draw bus",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "place_compile_mask",
        category: "place",
        label: "Place Compile Mask directive",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "place_design_block",
        category: "place",
        label: "Place design block",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "place_global_label",
        category: "place",
        label: "Place global label",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "place_hierarchical_label",
        category: "place",
        label: "Place hierarchical label",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "place_junction",
        category: "place",
        label: "Place junction",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "place_local_net_label",
        category: "place",
        label: "Place local net label",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "place_net_label",
        category: "place",
        label: "Place net label",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "place_no_connect",
        category: "place",
        label: "Place no-connect flag",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "place_no_erc",
        category: "place",
        label: "Place Generic No ERC directive",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "place_power_symbol",
        category: "place",
        label: "Place power symbol",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "place_symbol",
        category: "place",
        label: "Place symbol",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "place_text",
        category: "place",
        label: "Place text",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "place_wire",
        category: "place",
        label: "Place wire",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "place_wire_to_bus_entry",
        category: "place",
        label: "Place wire-to-bus entry",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "previous_highlighted_net_item",
        category: "select",
        label: "Previous item on highlighted net",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "previous_sheet",
        category: "navigation",
        label: "Previous sheet",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "run_erc",
        category: "validation",
        label: "Run electrical rules check",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "reset_schematic_designators",
        category: "design",
        label: "Reset schematic designators",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "sheet_navigation_back",
        category: "navigation",
        label: "Sheet navigation back",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "sheet_navigation_forward",
        category: "navigation",
        label: "Sheet navigation forward",
        group: CommandGroup::Schematic,
    },
    CommandMetadata {
        id: "update_pcb_from_schematic",
        category: "pcb_sync",
        label: "Update PCB from schematic",
        group: CommandGroup::Schematic,
    },
];
