use super::*;

#[derive(Debug, Clone)]
pub enum GerberViewerMessage {
    NoOp,
    DockEvent(iced_dock::DockEvent<GerberDockPanel>),
    NewDocument,
    CloseRequested,
    OpenFiles,
    FilesChosen(Option<Vec<PathBuf>>),
    FilesLoaded(GerberLoadBatch),
    ReloadAllLayers,
    LayersReloaded(signex_gerber::GerberReloadBatch),
    SelectLayer(usize),
    NextLayer,
    PreviousLayer,
    MoveLayerUp,
    MoveLayerDown,
    SetLayerVisible(usize, bool),
    ToggleColorPicker(GerberColorTarget),
    CloseColorPicker,
    SetLayerColor(usize, usize),
    SetGridColor(usize),
    SetDCodeColor(usize),
    SetNegativeObjectColor(usize),
    ClearCurrentLayer,
    ClearAllLayers,
    RedrawViewport,
    ToggleSketchFlashes,
    ToggleSketchLines,
    ToggleSketchPolygons,
    ToggleGhostNegativeObjects,
    ToggleDCodeLabels,
    ToggleCompareMode,
    ToggleForcedOpacityMode,
    ToggleDimInactiveLayers,
    ToggleMirrored,
    ZoomBy(f32),
    PanBy(iced::Vector),
    FitPage,
    ToggleLayerManager,
    ToggleHighlightPanel,
    ToggleGridPanel,
    ToggleLayerInformation,
    ToggleDCodeList,
    ToggleSourceView,
    SelectGridSize(usize),
    OpenGridEditor,
    NewGridNameChanged(String),
    NewGridXChanged(String),
    NewGridYChanged(String),
    SetNewGridUnitMillimetres(bool),
    CreateGridDefinition,
    DeleteGridDefinition,
    MoveGridUp,
    MoveGridDown,
    EditGridNameChanged(String),
    EditGridXChanged(String),
    EditGridYChanged(String),
    SetEditGridUnitMillimetres(bool),
    UpdateGridDefinition,
    ToggleGridVisibility(bool),
    SetDisplayUnit(GerberDisplayUnit),
    CycleDisplayUnit,
    CursorWorldPositionChanged(Option<signex_gerber::Point>),
    ActivateSelectionTool,
    ActivateMeasurementTool,
    ToggleMeasurement,
    BeginMeasurement(signex_gerber::Point),
    UpdateMeasurement(signex_gerber::Point),
    CompleteMeasurement(signex_gerber::Point),
    CaptureMeasurementPoint(signex_gerber::Point),
    ResetMeasurement,
    ToggleFullWindowCrosshair(bool),
    CycleCrosshairMode,
    SetPageSize(GerberPageSize),
    PrintVisibleLayers,
    GerberPrintFinished(Result<PathBuf, String>),
    ExportNativePcb,
    NativePcbPathChosen(Option<PathBuf>),
    NativePcbExportFinished(Result<(PathBuf, String), String>),
    ToggleZoomSelection,
    SetHighlightedComponent(String),
    ClearComponentHighlight,
    SetHighlightedNet(String),
    ClearNetHighlight,
    SetHighlightedAttribute(GerberAttributeValue),
    ClearAttributeHighlight,
    SetHighlightedDCode(i32),
    ClearDCodeHighlight,
    ClearHighlight,
    SetSelectedItem(Option<GerberItemSelection>),
    SetRegionSelection(Vec<GerberItemSelection>),
    ZoomToSelection { bounds: Bounds, viewport: Rectangle },
}

impl GerberViewerMessage {
    pub fn document_closed(document_id: GerberDocumentId) -> Self {
        Self::DockEvent(iced_dock::DockEvent::TabClosed {
            panel: GerberDockPanel::Document(document_id),
        })
    }
}
